### ISSUE TITLE
HOW?!

### ISSUE THREAD

**Issue by JeffAxe123** [ENDERZOMBI102/LoaderComplex#2]
Where is the download for this? 
Is this a launcher?
Is it a "modloader"?
Is it a fabric mod/forge mod?

How does it connect loaders? Are forge and fabric mods comptaiable?

Or is this just a troll?

**Comment by ENDERZOMBI102** [comment]
there's none
no
no
yes
it uses abraction,  ex. different frontend, same backend
no, its not a troll
